#!/bin/sh

# Stop on errors
set -e

# Creating Startup Link
echo "Registering as startup application..."
echo "[Desktop Entry]" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Type=Application" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Exec=sh /usr/bin/bingwallpaper" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Hidden=false" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "NoDisplay=false" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "X-GNOME-Autostart-enabled=true" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Name=Bing Wallpaper" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Comment=Bing Pic of the day as wallpaper." >> "$HOME/.config/autostart/bingwallpaper.desktop"

# Misc Info
echo "All the images will everntually be available at: $HOME/Pictures/Bing/"

# Firing app (not working)
#echo "Starting Application"
#sudo -u $SUDO_USER -c /usr/local/bin/bingwallpaper/bing_wallpaper.sh

echo "Bing wallpaper will be updated on next reboot. Or you can..."
echo "Run \"sh /usr/bin/bingwallpaper\" to update wallpaper now."

#DEBHELPER#
