#!/bin/sh

# Stop on errors.
set -e

# Deleting existing config.
rm -f "$HOME/.config/autostart/bingwallpaper.desktop"

# Creating Startup Link.
echo $HOME
echo "Registering as startup application..."
echo "[Desktop Entry]" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Type=Application" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Exec=sh /usr/bin/bingwallpaper" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Hidden=false" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "NoDisplay=false" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "X-GNOME-Autostart-enabled=true" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Name=Bing Wallpaper" >> "$HOME/.config/autostart/bingwallpaper.desktop"
echo "Comment=Bing Pic of the day as wallpaper." >> "$HOME/.config/autostart/bingwallpaper.desktop"

# Misc Info.
echo "All the images will everntually be available at: $HOME/Pictures/Bing/"
echo "Bing wallpaper will be updated on next reboot."
echo "Run \"bingwallpaper\" to update wallpaper now."

#DEBHELPER#
